In [17]:
import pandas as pd
import numpy as np

In [18]:
df=pd.read_csv("Fertilizer Prediction.csv");
df

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous,Fertilizer Name
0,26,52,38,Sandy,Maize,37,0,0,Urea
1,29,52,45,Loamy,Sugarcane,12,0,36,DAP
2,34,65,62,Black,Cotton,7,9,30,14-35-14
3,32,62,34,Red,Tobacco,22,0,20,28-28
4,28,54,46,Clayey,Paddy,35,0,0,Urea
...,...,...,...,...,...,...,...,...,...
94,25,50,32,Clayey,Pulses,24,0,19,28-28
95,30,60,27,Red,Tobacco,4,17,17,10-26-26
96,38,72,51,Loamy,Wheat,39,0,0,Urea
97,36,60,43,Sandy,Millets,15,0,41,DAP
98,29,58,57,Black,Sugarcane,12,0,10,20-20

In [19]:
from sklearn.preprocessing import LabelEncoder
le_Soil=LabelEncoder()
df["Soil Type"]=le_Soil.fit_transform(df["Soil Type"])
df["Soil Type"].unique()

array([4, 2, 0, 3, 1])

In [20]:
from sklearn.preprocessing import LabelEncoder
le_Crop=LabelEncoder()
df["Crop Type"]=le_Soil.fit_transform(df["Crop Type"])
df["Crop Type"].unique()

array([ 3,  8,  1,  9,  6,  0, 10,  4,  5,  7,  2])

In [21]:

X = df.drop("Fertilizer Name", axis=1)
y = df["Fertilizer Name"]

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.1,random_state=2)

In [23]:
from sklearn.ensemble import RandomForestClassifier
model123= RandomForestClassifier();
model123.fit(X_train, y_train)
y_pred = model123.predict(X_test)
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.9666666666666667

In [24]:
from sklearn.linear_model import LogisticRegression
model12=LogisticRegression()

model12.fit(X_train,y_train)

y_pred12=model12.predict(X_test)
score2=accuracy_score(y_test,y_pred12)
score2

C:\Users\acer\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

1.0

In [27]:
X=np.array([[26,52,38,"Sandy","Maize",37,0,0]]);

X[:,3]=le_Soil.transform(X[:,3])
X[:,4]=le_Crop.transform(X[:,4])
X=X.astype(float)
X

ValueError: y contains previously unseen labels: 'Sandy'

In [157]:
import pickle

In [158]:
with open("logisticRegression.pkl","wb") as file:
    pickle.dump(model12,file)

,Temparature,Humidity,Moisture,Soil Type,Crop Type,Nitrogen,Potassium,Phosphorous
0,26,52,38,4,3,37,0,0
1,29,52,45,2,8,12,0,36
2,34,65,62,0,1,7,9,30
3,32,62,34,3,9,22,0,20
4,28,54,46,1,6,35,0,0
...,...,...,...,...,...,...,...,...
94,25,50,32,1,7,24,0,19
95,30,60,27,3,9,4,17,17
96,38,72,51,2,10,39,0,0
97,36,60,43,4,4,15,0,41
98,29,58,57,0,8,12,0,10